env:
  es6: true
  mocha: true
  node: true

extends: 'eslint:recommended'

parserOptions:
  ecmaVersion: 8
  sourceType: module

rules:
  indent:
    - error
    - 2
    - SwitchCase: 1
  linebreak-style:
    - error
    - unix
  no-console: off
  no-control-regex: off
  no-trailing-spaces: 2
  quotes:
    - error
    - single
#  semi:
#    - error
#    - never
