env:
  es6: true
  mocha: true
  node: true

extends: 'eslint:recommended'

parserOptions:
  sourceType: module

rules:
  indent:
    - error
    - 2
    - SwitchCase: 1
  linebreak-style:
    - error
    - unix
  no-console: off
  no-control-regex: off
  no-undef: 1
  quotes:
    - error
    - single
#  semi:
#    - error
#    - never
