branch-defaults:
  default:
    environment: null
    group_suffix: null
  master:
    environment: api-dev
  production:
    environment: api-prod
global:
  application_name: WECO
  default_platform: Node.js
  default_region: eu-west-1
  profile: weco
  sc: null
