branch-defaults:
  default:
    environment: null
    group_suffix: null
  master:
    environment: null
    group_suffix: null
  production:
    environment: Weco-api-prod
global:
  application_name: WECO
  default_platform: Node.js
  default_region: eu-west-1
  profile: weco-iam
  sc: null
